language: node_js
node_js:
  - 13.3.0
script: echo "Testing temporarily disabled"
before_deploy:
- openssl aes-256-cbc -d -a -in credentials/lastfmConfig.json.enc -out credentials/lastfmConfig.json -k $AES_PASS
deploy:
  provider: script
  script: bash scripts/deploy $AES_PASS
  on:
    branch: master
branches:
  only:
  - master
  - development
